name:                advent-of-code-api
version:             0.2.8.0
github:              "mstksg/advent-of-code-api"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.0

extra-source-files:
- README.md
- CHANGELOG.md
- test-data/*.txt

# Metadata used when publishing your package
synopsis:            Advent of Code REST API bindings and servant API
category:            Web

description: |
  Haskell bindings for Advent of Code REST API and a servant API.  Please use
  responsibly! See README.md or "Advent" module for an introduction and
  tutorial.

ghc-options:
- -Wall
- -Wcompat
- -Werror=incomplete-patterns

dependencies:
- base >= 4.9 && < 5
- text
- directory
- filepath

library:
  source-dirs: src
  other-modules:
  - Advent.Throttle
  - Advent.Cache
  dependencies:
  - aeson
  - bytestring
  - containers
  - deepseq
  - finite-typelits
  - http-api-data
  - http-client
  - http-client-tls
  - http-media
  - megaparsec >= 7
  - mtl
  - profunctors
  - servant
  - servant-client
  - servant-client-core
  - stm
  - tagsoup
  - time
  - time-compat >= 1.9

tests:
  advent-of-code-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-api
    - HUnit
